name: test the actions

on:
  workflow_dispatch

jobs:
  print-hello-world:
    name: Print Hello world
    runs-on: ubuntu-latest
    environment: test
    steps: 
      - id: name
        env:
          EVENT_INFO: ${{ toJSON(github.event) }}
        run: |
          echo "This is my action"
          echo "${{ secrets.GITHUB_TOKEN }}"
          echo "$EVENT_INFO"
  
