name: test the actions

on:
  workflow_dispatch

jobs:
  print-hello-world:
    name: Print Hello world
    runs-on: ubuntu-latest
    steps: 
      - id: name
        env:
          GITHUB_TOKEN : ${{GITHUB_TOKEN}}
        run: |
          echo "This is my action"
          echo "${{GITHUB_TOKEN}}
  
