name: test the actions

on:
  workflow_dispatch

jobs:
  print-hello-world:
    name: Print Hello world
    runs-on: ubuntu-latest
    steps: 
      - id: name
        env:
          GH_TOKEN : ${{ secrets.GITHUB_TOKEN }}
        run: |
          echo "This is my action"
          echo "${{GH_TOKEN}}"
  
