name: test the actions

on:
  workflow_dispatch

jobs:
  print-hello-world:
    name: Print Hello world
    runs-on: ubuntu-latest
    environment: test
    steps: 
      - id: set_name
        name: Set the name
        run: |
          echo "This is my action"
          echo "name=malai" >> $GITHUB_ENV
      - id: get_name
        name: Get the name
        run: |
          echo $name
  
